import type { InventoryModel } from "@/models/inventory_model";

export const InventoryService = {
  getAllInventory() {
    return [
      {
        code: "INV-001",
        name: "Premium Bath Towel",
        decscription: "Soft white cotton bath towel, 70x140cm",
        quantity: 0,
        price: 15.0,
        total_price: 3000.0,
        image: "https://placehold.co/300x200?text=Bath+Towel",
        category: "Housekeeping",
        supplier: "Hotel Linen Supply",
        date: "2023-10-01",
        status: "Low Stock",
        created_by: "Admin",
        created_at: new Date("2023-10-01"),
        updated_by: "Admin",
        updated_at: new Date("2023-10-01"),
      },
      {
        code: "INV-002",
        name: "Luxury Shampoo",
        decscription: "50ml bottle, aloe vera scent",
        quantity: 500,
        price: 2.5,
        total_price: 1250.0,
        image: "https://placehold.co/300x200?text=Shampoo",
        category: "Housekeeping",
        supplier: "Guest Amenities Inc.",
        date: "2023-10-02",
        status: "In Stock",
        created_by: "Admin",
        created_at: new Date("2023-10-02"),
        updated_by: "Admin",
        updated_at: new Date("2023-10-02"),
      },
      {
        code: "INV-003",
        name: "Organic Bar Soap",
        decscription: "25g bar, lavender scent",
        quantity: 600,
        price: 1.2,
        total_price: 720.0,
        image: "https://placehold.co/300x200?text=Soap",
        category: "Housekeeping",
        supplier: "Guest Amenities Inc.",
        date: "2023-10-03",
        status: "In Stock",
        created_by: "Admin",
        created_at: new Date("2023-10-03"),
        updated_by: "Admin",
        updated_at: new Date("2023-10-03"),
      },
      {
        code: "INV-004",
        name: "King Size Bed Sheet",
        decscription: "White satin stripe, 300 thread count",
        quantity: 50,
        price: 45.0,
        total_price: 2250.0,
        image: "https://placehold.co/300x200?text=Bed+Sheet",
        category: "Housekeeping",
        supplier: "Hotel Linen Supply",
        date: "2023-10-04",
        status: "In Stock",
        created_by: "Admin",
        created_at: new Date("2023-10-04"),
        updated_by: "Admin",
        updated_at: new Date("2023-10-04"),
      },
      {
        code: "INV-005",
        name: "Soft Pillow",
        decscription: "Synthetic down alternative, standard size",
        quantity: 80,
        price: 22.0,
        total_price: 1760.0,
        image: "https://placehold.co/300x200?text=Pillow",
        category: "Housekeeping",
        supplier: "Hotel Linen Supply",
        date: "2023-10-05",
        status: "In Stock",
        created_by: "Admin",
        created_at: new Date("2023-10-05"),
        updated_by: "Admin",
        updated_at: new Date("2023-10-05"),
      },
      {
        code: "INV-006",
        name: "Dental Kit",
        decscription: "Toothbrush and 5g toothpaste",
        quantity: 400,
        price: 0.8,
        total_price: 320.0,
        image: "https://placehold.co/300x200?text=Dental+Kit",
        category: "Housekeeping",
        supplier: "Guest Amenities Inc.",
        date: "2023-10-06",
        status: "Low Stock",
        created_by: "Manager",
        created_at: new Date("2023-10-06"),
        updated_by: "Manager",
        updated_at: new Date("2023-10-06"),
      },
      {
        code: "INV-007",
        name: "Mineral Water 500ml",
        decscription: "Still mineral water, plastic bottle",
        quantity: 1000,
        price: 0.5,
        total_price: 500.0,
        image: "https://placehold.co/300x200?text=Water",
        category: "F&B",
        supplier: "Beverage Distributors",
        date: "2023-10-07",
        status: "In Stock",
        created_by: "Staff",
        created_at: new Date("2023-10-07"),
        updated_by: "Staff",
        updated_at: new Date("2023-10-07"),
      },
      {
        code: "INV-008",
        name: "Arabica Coffee Beans",
        decscription: "1kg bag, medium roast",
        quantity: 20,
        price: 18.0,
        total_price: 360.0,
        image: "https://placehold.co/300x200?text=Coffee",
        category: "F&B",
        supplier: "Local Roastery",
        date: "2023-10-08",
        status: "In Stock",
        created_by: "Staff",
        created_at: new Date("2023-10-08"),
        updated_by: "Staff",
        updated_at: new Date("2023-10-08"),
      },
      {
        code: "INV-009",
        name: "Green Tea Bags",
        decscription: "Box of 100 tea bags",
        quantity: 30,
        price: 8.5,
        total_price: 255.0,
        image: "https://placehold.co/300x200?text=Tea",
        category: "F&B",
        supplier: "Beverage Distributors",
        date: "2023-10-09",
        status: "In Stock",
        created_by: "Staff",
        created_at: new Date("2023-10-09"),
        updated_by: "Staff",
        updated_at: new Date("2023-10-09"),
      },
      {
        code: "INV-010",
        name: "Toilet Paper Roll",
        decscription: "3-ply, pack of 10",
        quantity: 200,
        price: 5.0,
        total_price: 1000.0,
        image: "https://placehold.co/300x200?text=Toilet+Paper",
        category: "Housekeeping",
        supplier: "Clean Supplies Ltd.",
        date: "2023-10-10",
        status: "In Stock",
        created_by: "Admin",
        created_at: new Date("2023-10-10"),
        updated_by: "Admin",
        updated_at: new Date("2023-10-10"),
      },
      {
        code: "INV-011",
        name: "Multi-surface Cleaner",
        decscription: "5L canister, lemon scent",
        quantity: 15,
        price: 12.0,
        total_price: 180.0,
        image: "https://placehold.co/300x200?text=Cleaner",
        category: "Maintenance",
        supplier: "Clean Supplies Ltd.",
        date: "2023-10-11",
        status: "In Stock",
        created_by: "Manager",
        created_at: new Date("2023-10-11"),
        updated_by: "Manager",
        updated_at: new Date("2023-10-11"),
      },
      {
        code: "INV-012",
        name: "LED Light Bulb 9W",
        decscription: "E27 screw base, warm white",
        quantity: 100,
        price: 3.5,
        total_price: 350.0,
        image: "https://placehold.co/300x200?text=Light+Bulb",
        category: "Maintenance",
        supplier: "Hardware Solutions",
        date: "2023-10-12",
        status: "In Stock",
        created_by: "Manager",
        created_at: new Date("2023-10-12"),
        updated_by: "Manager",
        updated_at: new Date("2023-10-12"),
      },
      {
        code: "INV-013",
        name: "Ballpoint Pen",
        decscription: "Blue ink, box of 50",
        quantity: 20,
        price: 10.0,
        total_price: 200.0,
        image: "https://placehold.co/300x200?text=Pen",
        category: "Office",
        supplier: "Office Depot",
        date: "2023-10-13",
        status: "In Stock",
        created_by: "Admin",
        created_at: new Date("2023-10-13"),
        updated_by: "Admin",
        updated_at: new Date("2023-10-13"),
      },
      {
        code: "INV-014",
        name: "A4 Paper Ream",
        decscription: "80gsm, 500 sheets",
        quantity: 40,
        price: 4.5,
        total_price: 180.0,
        image: "https://placehold.co/300x200?text=Paper",
        category: "Office",
        supplier: "Office Depot",
        date: "2023-10-14",
        status: "In Stock",
        created_by: "Admin",
        created_at: new Date("2023-10-14"),
        updated_by: "Admin",
        updated_at: new Date("2023-10-14"),
      },
      {
        code: "INV-015",
        name: "Disposable Slippers",
        decscription: "White open-toe slippers",
        quantity: 300,
        price: 1.5,
        total_price: 450.0,
        image: "https://placehold.co/300x200?text=Slippers",
        category: "Housekeeping",
        supplier: "Guest Amenities Inc.",
        date: "2023-10-15",
        status: "In Stock",
        created_by: "Staff",
        created_at: new Date("2023-10-15"),
        updated_by: "Staff",
        updated_at: new Date("2023-10-15"),
      },
      {
        code: "INV-016",
        name: "Cotton Bathrobe",
        decscription: "Waffle weave, one size fits all",
        quantity: 50,
        price: 35.0,
        total_price: 1750.0,
        image: "https://placehold.co/300x200?text=Bathrobe",
        category: "Housekeeping",
        supplier: "Hotel Linen Supply",
        date: "2023-10-16",
        status: "In Stock",
        created_by: "Manager",
        created_at: new Date("2023-10-16"),
        updated_by: "Manager",
        updated_at: new Date("2023-10-16"),
      },
      {
        code: "INV-017",
        name: "Wooden Hanger",
        decscription: "Natural wood with trouser bar",
        quantity: 200,
        price: 1.8,
        total_price: 360.0,
        image: "https://placehold.co/300x200?text=Hanger",
        category: "Housekeeping",
        supplier: "Hotel Linen Supply",
        date: "2023-10-17",
        status: "In Stock",
        created_by: "Staff",
        created_at: new Date("2023-10-17"),
        updated_by: "Staff",
        updated_at: new Date("2023-10-17"),
      },
      {
        code: "INV-018",
        name: "Trash Bags 50L",
        decscription: "Heavy duty, roll of 20",
        quantity: 100,
        price: 3.0,
        total_price: 300.0,
        image: "https://placehold.co/300x200?text=Trash+Bags",
        category: "Maintenance",
        supplier: "Clean Supplies Ltd.",
        date: "2023-10-18",
        status: "In Stock",
        created_by: "Manager",
        created_at: new Date("2023-10-18"),
        updated_by: "Manager",
        updated_at: new Date("2023-10-18"),
      },
      {
        code: "INV-019",
        name: "Laundry Detergent",
        decscription: "20L drum, industrial grade",
        quantity: 10,
        price: 45.0,
        total_price: 450.0,
        image: "https://placehold.co/300x200?text=Detergent",
        category: "Housekeeping",
        supplier: "Clean Supplies Ltd.",
        date: "2023-10-19",
        status: "In Stock",
        created_by: "Manager",
        created_at: new Date("2023-10-19"),
        updated_by: "Manager",
        updated_at: new Date("2023-10-19"),
      },
      {
        code: "INV-020",
        name: "Mini Bar Snacks",
        decscription: "Assorted nuts and chips",
        quantity: 150,
        price: 2.0,
        total_price: 300.0,
        image: "https://placehold.co/300x200?text=Snacks",
        category: "F&B",
        supplier: "Snack Vendors",
        date: "2023-10-20",
        status: "In Stock",
        created_by: "Staff",
        created_at: new Date("2023-10-20"),
        updated_by: "Staff",
        updated_at: new Date("2023-10-20"),
      },
    ] as InventoryModel[];
  },
};
