import type { SupplierModel } from "@/models/supplier.model";

export const SupplierService = {
  getAllSupplier() {
    return <SupplierModel[]>[
      {
        SupplierCode: "S001",
        SupplierName: "អ្នកផ្គត់ផ្គង់ 1",
        Description: "ការពិពណ៌នា 1",
        Address: "អាសយដ្ឋាន 1",
        Phone: "ទូរស័ព្ទ 1",
        Email: "អ៊ីមែល 1",
        Status: true,
        CreatedAt: new Date(),
        CreatedBy: "អ្នកបង្កើត 1",
        UpdatedAt: new Date(),
        UpdatedBy: "អ្នកបន្ទាន់តែ 1",
      },
      {
        SupplierCode: "S002",
        SupplierName: "អ្នកផ្គត់ផ្គង់ 2",
        Description: "ការពិពណ៌នា 2",
        Address: "អាសយដ្ឋាន 2",
        Phone: "ទូរស័ព្ទ 2",
        Email: "អ៊ីមែល 2",
        Status: true,
        CreatedAt: new Date(),
        CreatedBy: "អ្នកបង្កើត 2",
        UpdatedAt: new Date(),
        UpdatedBy: "អ្នកបន្ទាន់តែ 2",
      },
      {
        SupplierCode: "S003",
        SupplierName: "អ្នកផ្គត់ផ្គង់ 3",
        Description: "ការពិពណ៌នា 3",
        Address: "អាសយដ្ឋាន 3",
        Phone: "ទូរស័ព្ទ 3",
        Email: "អ៊ីមែល 3",
        Status: false,
        CreatedAt: new Date(),
        CreatedBy: "អ្នកបង្កើត 3",
        UpdatedAt: new Date(),
        UpdatedBy: "អ្នកបន្ទាន់តែ 3",
      },
      {
        SupplierCode: "S004",
        SupplierName: "អ្នកផ្គត់ផ្គង់ 4",
        Description: "ការពិពណ៌នា 4",
        Address: "អាសយដ្ឋាន 4",
        Phone: "ទូរស័ព្ទ 4",
        Email: "អ៊ីមែល 4",
        Status: true,
        CreatedAt: new Date(),
        CreatedBy: "អ្នកបង្កើត 4",
        UpdatedAt: new Date(),
        UpdatedBy: "អ្នកបន្ទាន់តែ 4",
      },
      {
        SupplierCode: "S005",
        SupplierName: "អ្នកផ្គត់ផ្គង់ 5",
        Description: "ការពិពណ៌នា 5",
        Address: "អាសយដ្ឋាន 5",
        Phone: "ទូរស័ព្ទ 5",
        Email: "អ៊ីមែល 5",
        Status: true,
        CreatedAt: new Date(),
        CreatedBy: "អ្នកបង្កើត 5",
        UpdatedAt: new Date(),
        UpdatedBy: "អ្នកបន្ទាន់តែ 5",
      },
      {
        SupplierCode: "S006",
        SupplierName: "អ្នកផ្គត់ផ្គង់ 6",
        Description: "ការពិពណ៌នា 6",
        Address: "អាសយដ្ឋាន 6",
        Phone: "ទូរស័ព្ទ 6",
        Email: "អ៊ីមែល 6",
        Status: true,
        CreatedAt: new Date(),
        CreatedBy: "អ្នកបង្កើត 6",
        UpdatedAt: new Date(),
        UpdatedBy: "អ្នកបន្ទាន់តែ 6",
      },
      {
        SupplierCode: "S007",
        SupplierName: "អ្នកផ្គត់ផ្គង់ 7",
        Description: "ការពិពណ៌នា 7",
        Address: "អាសយដ្ឋាន 7",
        Phone: "ទូរស័ព្ទ 7",
        Email: "អ៊ីមែល 7",
        Status: true,
        CreatedAt: new Date(),
        CreatedBy: "អ្នកបង្កើត 7",
        UpdatedAt: new Date(),
        UpdatedBy: "អ្នកបន្ទាន់តែ 7",
      },
      {
        SupplierCode: "S008",
        SupplierName: "អ្នកផ្គត់ផ្គង់ 8",
        Description: "ការពិពណ៌នា 8",
        Address: "អាសយដ្ឋាន 8",
        Phone: "ទូរស័ព្ទ 8",
        Email: "អ៊ីមែល 8",
        Status: false,
        CreatedAt: new Date(),
        CreatedBy: "អ្នកបង្កើត 8",
        UpdatedAt: new Date(),
        UpdatedBy: "អ្នកបន្ទាន់តែ 8",
      },
      {
        SupplierCode: "S009",
        SupplierName: "អ្នកផ្គត់ផ្គង់ 9",
        Description: "ការពិពណ៌នា 9",
        Address: "អាសយដ្ឋាន 9",
        Phone: "ទូរស័ព្ទ 9",
        Email: "អ៊ីមែល 9",
        Status: true,
        CreatedAt: new Date(),
        CreatedBy: "អ្នកបង្កើត 9",
        UpdatedAt: new Date(),
        UpdatedBy: "អ្នកបន្ទាន់តែ 9",
      },
      {
        SupplierCode: "S010",
        SupplierName: "អ្នកផ្គត់ផ្គង់ 10",
        Description: "ការពិពណ៌នា 10",
        Address: "អាសយដ្ឋាន 10",
        Phone: "ទូរស័ព្ទ 10",
        Email: "អ៊ីមែល 10",
        Status: true,
        CreatedAt: new Date(),
        CreatedBy: "អ្នកបង្កើត 10",
        UpdatedAt: new Date(),
        UpdatedBy: "អ្នកបន្ទាន់តែ 10",
      },
    ];
  },
};
