export const enum ROUTE_PATH {
  LOGIN = "/login",
  DASHBOARD = "/app/dashboard",
  ROOM = "/app/room",
  ROOM_TYPE = "/app/room-type",
  BOOKING = "/app/booking",
  HOME = "/home",
  SUPPLIER = "/supplier",
  STOCK = "/stock",
  ABOUT = "/about",
  RESERVATION = "/reservation",
  ROOM_CALENDAR = "/room-calendar",
  GUEST = "/guest",
  GUEST_HISTORY = "/guest-history",
}
